[tool.poetry]
name = "audiotext"
version = "0.1.0"
description = ""
authors = ["Hiram20buz"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
speechrecognition = "^3.10.1"
pyaudio = "^0.2.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
